spring.application.name=farmer
spring.datasource.url=jdbc:mysql://localhost:3306/farmer_retailer_db
spring.datasource.username=root
spring.datasource.password=Mysql@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

razorpay.key.id=rzp_test_S1iNDU4u6JLAoj
razorpay.key.secret=3ZZ3926M3pJMsoIxs5F6SHWI

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agricart.app@gmail.com
spring.mail.password=qdkt pxnq wgfi cahq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
